import prisma from '../src/lib/prisma';

async function main() {
  console.log('🌱 Début du seed de la base de données...');

  // Supprimer les données existantes
  await prisma.cardiovascularData.deleteMany();

  // Créer des données de test
  const testData = [
    // Patients sains jeunes
    {
      age: 35,
      sex: 1,
      angina: 4,
      bloodPressure: 120,
      cholesterol: 180,
      glycemia: 0,
      ecg: 0,
      heartRate: 150,
      anginaAfterSport: 0,
      ecgAngina: 0,
      ecgSlope: 1,
      fluoroscopy: 0,
      thalassemia: 3,
      disease: 0,
    },
    {
      age: 38,
      sex: 0,
      angina: 4,
      bloodPressure: 115,
      cholesterol: 190,
      glycemia: 0,
      ecg: 0,
      heartRate: 145,
      anginaAfterSport: 0,
      ecgAngina: 0,
      ecgSlope: 1,
      fluoroscopy: 0,
      thalassemia: 3,
      disease: 0,
    },
    // Patients à risque moyen
    {
      age: 45,
      sex: 1,
      angina: 3,
      bloodPressure: 135,
      cholesterol: 220,
      glycemia: 0,
      ecg: 1,
      heartRate: 140,
      anginaAfterSport: 0,
      ecgAngina: 0.5,
      ecgSlope: 2,
      fluoroscopy: 1,
      thalassemia: 3,
      disease: 0,
    },
    {
      age: 52,
      sex: 1,
      angina: 2,
      bloodPressure: 145,
      cholesterol: 240,
      glycemia: 1,
      ecg: 1,
      heartRate: 135,
      anginaAfterSport: 1,
      ecgAngina: 1.0,
      ecgSlope: 2,
      fluoroscopy: 1,
      thalassemia: 6,
      disease: 1,
    },
    // Patients malades
    {
      age: 58,
      sex: 1,
      angina: 1,
      bloodPressure: 160,
      cholesterol: 280,
      glycemia: 1,
      ecg: 2,
      heartRate: 125,
      anginaAfterSport: 1,
      ecgAngina: 2.5,
      ecgSlope: 3,
      fluoroscopy: 2,
      thalassemia: 7,
      disease: 2,
    },
    {
      age: 62,
      sex: 0,
      angina: 1,
      bloodPressure: 170,
      cholesterol: 300,
      glycemia: 1,
      ecg: 2,
      heartRate: 120,
      anginaAfterSport: 1,
      ecgAngina: 3.0,
      ecgSlope: 3,
      fluoroscopy: 3,
      thalassemia: 7,
      disease: 3,
    },
    {
      age: 65,
      sex: 1,
      angina: 1,
      bloodPressure: 180,
      cholesterol: 320,
      glycemia: 1,
      ecg: 2,
      heartRate: 110,
      anginaAfterSport: 1,
      ecgAngina: 3.5,
      ecgSlope: 3,
      fluoroscopy: 3,
      thalassemia: 7,
      disease: 4,
    },
    // Plus de patients pour la diversité
    {
      age: 42,
      sex: 0,
      angina: 4,
      bloodPressure: 125,
      cholesterol: 200,
      glycemia: 0,
      ecg: 0,
      heartRate: 148,
      anginaAfterSport: 0,
      ecgAngina: 0,
      ecgSlope: 1,
      fluoroscopy: 0,
      thalassemia: 3,
      disease: 0,
    },
    {
      age: 55,
      sex: 1,
      angina: 2,
      bloodPressure: 150,
      cholesterol: 250,
      glycemia: 1,
      ecg: 1,
      heartRate: 130,
      anginaAfterSport: 1,
      ecgAngina: 1.5,
      ecgSlope: 2,
      fluoroscopy: 2,
      thalassemia: 6,
      disease: 2,
    },
    {
      age: 48,
      sex: 0,
      angina: 3,
      bloodPressure: 140,
      cholesterol: 230,
      glycemia: 0,
      ecg: 1,
      heartRate: 138,
      anginaAfterSport: 0,
      ecgAngina: 0.8,
      ecgSlope: 2,
      fluoroscopy: 1,
      thalassemia: 3,
      disease: 1,
    },
    {
      age: 60,
      sex: 1,
      angina: 1,
      bloodPressure: 165,
      cholesterol: 290,
      glycemia: 1,
      ecg: 2,
      heartRate: 118,
      anginaAfterSport: 1,
      ecgAngina: 2.8,
      ecgSlope: 3,
      fluoroscopy: 2,
      thalassemia: 7,
      disease: 3,
    },
    {
      age: 33,
      sex: 0,
      angina: 4,
      bloodPressure: 118,
      cholesterol: 175,
      glycemia: 0,
      ecg: 0,
      heartRate: 152,
      anginaAfterSport: 0,
      ecgAngina: 0,
      ecgSlope: 1,
      fluoroscopy: 0,
      thalassemia: 3,
      disease: 0,
    },
    {
      age: 50,
      sex: 1,
      angina: 3,
      bloodPressure: 142,
      cholesterol: 235,
      glycemia: 0,
      ecg: 1,
      heartRate: 132,
      anginaAfterSport: 0,
      ecgAngina: 1.2,
      ecgSlope: 2,
      fluoroscopy: 1,
      thalassemia: 6,
      disease: 1,
    },
    {
      age: 67,
      sex: 0,
      angina: 1,
      bloodPressure: 175,
      cholesterol: 310,
      glycemia: 1,
      ecg: 2,
      heartRate: 115,
      anginaAfterSport: 1,
      ecgAngina: 3.2,
      ecgSlope: 3,
      fluoroscopy: 3,
      thalassemia: 7,
      disease: 4,
    },
    {
      age: 40,
      sex: 1,
      angina: 4,
      bloodPressure: 128,
      cholesterol: 195,
      glycemia: 0,
      ecg: 0,
      heartRate: 146,
      anginaAfterSport: 0,
      ecgAngina: 0,
      ecgSlope: 1,
      fluoroscopy: 0,
      thalassemia: 3,
      disease: 0,
    },
  ];

  for (const data of testData) {
    await prisma.cardiovascularData.create({
      data,
    });
  }

  console.log(`✅ ${testData.length} enregistrements créés avec succès`);
}

main()
  .catch((e) => {
    console.error('❌ Erreur lors du seed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
